server:
  port: 8073

spring:
  application:
    name: user
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  mail:
    host: smtp.gmail.com
    port: 587
    username: abderraouf.mahmoudi2001@gmail.com
    password: gkgrmdspjnvdplta
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

