   apiVersion: v1
  kind: Secret
  metadata:
    name: course-db-secret
  type: Opaque
  data:
    username: YWRtaW4= # Base64 encoded "admin"
    password: eW91cl9zZWN1cmVfcGFzc3dvcmQ= # Base64 encoded "your_secure_password" (update securely)
    db_name: Y291cnNlX2Ri # Base64 encoded "course_db"