#before
#aws secretsmanager create-secret --name user-db-secret --secret-string '{"username":"admin","password":"your_secure_password"}' --region us-west-1
#aws secretsmanager create-secret --name course-db-secret --secret-string '{"username":"admin","password":"your_secure_password"}' --region us-west-1
#kubectl apply -f kubernetes/user-secret.yml

#Ensure your IAM user has secretsmanager:* permissions.
apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
type: Opaque
data:
  username: YWRtaW4=          # Base64 encoded "admin"
  password: eW91cl9zZWN1cmVfcGFzc3dvcmQ=  # Base64 encoded "your_secure_password"
  db_name: dXNlcl9kYg==       # Base64 encoded "user_db"


#how to generate em use these commands basically
#echo -n 'admin' | base64
#echo -n 'your_secure_password' | base64
#echo -n 'user_db' | base64