spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id : r1
            uri: lb://COURS
            predicates:
              - Path=/api/courses/**
              - Path=/api/categories/**

          - id: r2
            uri: lb://USER
            predicates:
              - Path=/api/auth/**


  application:
    name: gateway-service
server:
  port: 8888