server:
  port: 8012
spring:
  application:
    name: offres
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/



