stages:
  - validate
  - test
  - plan
  - apply
  - build
  - deploy
  - rollback

default:
  image: hashicorp/terraform:latest
  before_script:
    - terraform init

validate:
  stage: validate
  script:
    - terraform validate
  except:
    - master

test:
  stage: test
  image: maven:3.8-openjdk-17
  script:
    - cd microservices/user
    - mvn test
    - cd ../course
    - mvn test
  only:
    - master

plan:
  stage: plan
  script:
    - terraform plan -var-file=terraform.tfvars -out=tfplan
  artifacts:
    paths:
      - tfplan
  only:
    - master

apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - plan
  only:
    - master

build:
  stage: build
  image: docker:20.10
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - cd microservices/user
    - docker build -t zeinebroihii/user-microservice:latest .
    - docker push zeinebroihii/user-microservice:latest
    - cd ../course
    - docker build -t zeinebroihii/course-microservice:latest .
    - docker push zeinebroihii/course-microservice:latest
  only:
    - master

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - export KUBECONFIG=$KUBECONFIG
    - export USER_DB_ENDPOINT=$(terraform output -raw user_db_endpoint)
    - export COURSE_DB_ENDPOINT=$(terraform output -raw course_db_endpoint)
  script:
    - sed -i "s|\${USER_DB_ENDPOINT}|$USER_DB_ENDPOINT|" kubernetes/user-deployment.yml
    - sed -i "s|\${COURSE_DB_ENDPOINT}|$COURSE_DB_ENDPOINT|" kubernetes/course-deployment.yml
    - kubectl apply -f kubernetes/user-secret.yml
    - kubectl apply -f kubernetes/course-secret.yml
    - kubectl apply -f kubernetes/user-deployment.yml
    - kubectl apply -f kubernetes/user-service.yml
    - kubectl apply -f kubernetes/course-deployment.yml
    - kubectl apply -f kubernetes/course-service.yml
    - kubectl apply -f kubernetes/unihelp-ingress.yml
  dependencies:
    - apply
    - build
  only:
    - master

rollback:
  stage: rollback
  image: bitnami/kubectl:latest
  when: manual
  before_script:
    - export KUBECONFIG=$KUBECONFIG
  script:
    - kubectl rollout undo deployment/user-deployment
    - kubectl rollout undo deployment/course-deployment
  only:
    - master